fix: undefined reference to `BT_SETUP`
BT_SETUP is in kernel.c, the definition was copied inside ppc64.c
since it was required by is_frame_num_valid

Signed-off-by: Aditya Gupta <adityag@ibm.com>